### ISSUE TITLE
Unit incoherence in info widget

### ISSUE THREAD

**Issue by ddennetiere** [lucarebuffi/ShadowOui#132]
It seems that the distance summary in the info widget does'nt take the units into account. The oe info tab does though.
It is confusing but not critical.

![oasys_oe_dist](https://cloud.githubusercontent.com/assets/22654323/19157786/be985f4e-8be6-11e6-9548-0696f4c63282.png)
![oasys_dist_summ](https://cloud.githubusercontent.com/assets/22654323/19157803/c5a6a14c-8be6-11e6-8ff9-f28ff47acc65.png)

**Comment by srio** [comment]
I think the problem is in

https://github.com/lucarebuffi/ShadowOui/blob/master/orangecontrib/shadow/widgets/plots/ow_info.py

when initializing the compound oe: 

coe_end = ShadowCompoundOpticalElement.create_compound_oe()

The units of the workspace should be passed: 

coe_end = ShadowCompoundOpticalElement.create_compound_oe(workspace_units_to_cm=???)
