### ISSUE TITLE
Ray index variable (11) must be reorganized whrn widgets create new beams

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#138]
Impacts:

- Hybrid (done)
- Merge Beam
- Beam Accumulating Point

**Comment by srio** [comment]
Do you need input from me?

I understand it is originated by a historic problem. 

Memorandum: 

internally shadow column 11 (beam.rays[:,10]) contains the modulus of the wavevector 2*pi/lambda in cm^-1. 

Since many years ago, the tools to access the arrays return the energy in eV: beam.getshcol(11)

I believe this is not elegant and it would have been better to define a new column with the energy in eV. But we cannot change this behavior as will affect all users. 

So the solution is to access directly the rays array. If wanted we can add a new method in beam
beam.setshcol(11,energies_in_eV)

Sorry for that!!

**Comment by lucarebuffi** [comment]
I was referring to shadow column 12 (ray index). There are widgets that "clean" the lost rays from the beam (hybrid, beam accumulating) or merge more beams. In that case the variable lost its connection with the beam and potentially creates inconsistency (as happened with hybrid). I do not need assistance, thank you!

**Comment by lucarebuffi** [comment]
Sorry for being that unclear. By the way we have a new issue to write :D
