### ISSUE TITLE
Hybrid not working with loaded source file

### ISSUE THREAD

**Issue by xianbo** [lucarebuffi/ShadowOui#142]
Hybrid does not work if use a shadow file reader to pass a beam. It shows an error "list index out of range".
To see this error, simply use a geometric source and a shadow file writer to save a "begin_test.dat" file or whatever name. Then use a shadow file reader to read the file and pass it to a slit screen and attach a hybrid screen to it. 
It is the same for all hybrid types. Also, it is the same no mater how may OE are between the shadow file reader and the hybrid screen.

**Comment by lucarebuffi** [comment]
could you please attach the workspace and files?

**Comment by xianbo** [comment]
[hybrid_problem_1.zip](https://github.com/lucarebuffi/ShadowOui/files/600754/hybrid_problem_1.zip)

**Comment by lucarebuffi** [comment]
The problem was that the read file widget recreate a beam without any history. I added the creation of a fake history: 
Source: impossible to recreate, just added an empty history element with oe_number =0
"Safety" OE: "pass-through" Empty OE, with 0 distances (source and image planes) and 0-180 incidence-reflection angles.
The safety OE ensures any possible re-tracing algorithms from history (as Hybrid does in some cases) and prevents the usage of the fake empty source.

Please test it.

**Comment by lucarebuffi** [comment]
It is more difficoult to explain than to understand....I'm sorry
