### ISSUE TITLE
about waviness

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#147]
Dear Luca,
if I use  waviness for a crystal, it gives a warning  "This O.E. is not a mirror or grating: surface error file will be ignored".   does that mean it is meaningless using waviness file for a crystal  ?

Yajun Tong

**Comment by lucarebuffi** [comment]
There are two things that must be said:

1 - Don't use Waviness, it is there only for historical reasons. It has been replaced with the much more reliable tools Height Profile Simulator and DABAM

2 - The surface error profile it is generally considered meaningless for a crystal that works in diffraction. I also discourage it because, by considering how shadow works, it can lead to fake results.
The meaning of a surface error for a crystal, by a algorithmic point of view, is completely different, and is generally used to take into account deformations on the crystalline planes (ex: twist effects or anticlastic curvature on a bendable crystal).

Shadow3 calculate the incident and reflected angle by calculating the normal at the surface according to the shape of the optical element + a correction for the surface error. In case of reflection it means that it takes into account polishing errors (it applies the law of reflection), but in case of crystals it means that it takes into account deformation of the crystalline planes, since it applies diffraction laws.

**Comment by tyjisinap** [comment]
Thank you very much!
