### ISSUE TITLE
parabolic mirror

### ISSUE THREAD

**Issue by paramirror** [lucarebuffi/ShadowOui#150]
Dear all,
since a few days I get familar with the nice "ShadowOui" package. Thanks a lot for providing this nice program.
Meanwhile for me it's comparatively easy to handle and I enjoy the flexibility and clear structure of the program when simulating beamline components.

1)
I have a problem with focussing using parabolic mirror....
My interpretation of the parabolic mirror is:
one dimension (length) is formed like a parabola & the other dimension is cylindrically/sperically shaped

If this would be correct, the example in the attachment should give a focal SPOT in the focal plane – (2D focussing)
when using parab. and ellipt. mirrors.
Unfortunately I am able to obtain 2D focussing only with toroidal mirrors. with paraboloid it is line focussing (1D) only.

Is my interpretation of the "paraboloid" correct??

if YES : how the existing example  (attachment) can be modified to obtain 2D focussing for parab. case?? 
if NOT:  
- what is the meaning of the „cylinder parameter“ – is it only used for defining the orientation of the reflection plane - horizontally/vertically ??
- paraboloid is the name for a surface curved in TWO dimensions (sherical or elliptical in the 2nd) – than the name would be misleading 
- could the 2D focussing  feature be implemented in future for this elements??

the file in the attachment shows an example 
first mirror is for collimation and second for focussing - 

2)
Another unclear behavior of the program:
Toroidal mirror:
- When defining the limits in the dimensions of the toroid, a double curved surface is displayed. When rendering the surface shape with "limit checks on" - a single curved surface is displayed.
- The re-calulation of the maj. and min. radius of the toroid is done after "enter" or "run shadow" and is not done when clicking on "render surface shape"

I think similar is true for elliptical mirror

Many thanks for your help

**Comment by paramirror** [comment]
[test_EL_PA_TO.zip](https://github.com/lucarebuffi/ShadowOui/files/618696/test_EL_PA_TO.zip)

**Comment by lucarebuffi** [comment]
Dear Paramirror,

Let's consider the first point, the paraboloid widget gives you a paraboloid or a cylindric mirror with parabolic profile, according to the value of the parameter "Cylindrical: Yes/No". If you need 2D focusing, simply put "cylinder=No".
In your example, let's consider the first paraboloid:

this is the spot at the focus location (5000000.0 cm) in your original simulation:

![screen shot 2016-11-29 at 12 25 32](https://cloud.githubusercontent.com/assets/6713598/20708159/028683ee-b62f-11e6-8329-cd3eb670acaf.png)

but selecting No in the "cylinder" parameter you will obtain this:

![screen shot 2016-11-29 at 12 25 46](https://cloud.githubusercontent.com/assets/6713598/20708162/09fbd6f6-b62f-11e6-8ea1-0852ca6767f9.png)

and there it is. The cylinder orientation allows you to specify where the cylindric shape is: 0 the parabola is in the tangential plane, 90 is in the sagittal plane. Ex: a vertically collimating mirror,  before a double crystal monochromator, will have 0 cylinder orientation, since the parabola shape is in the tangential plane, while a bendable sagittally focusing crystal will have 90 cylinder orientation.
This rule is identical for all the other shapes, except Thorus, of course.
Nomenclature we adopted is historical, belongs to Shadow since its first coding (in the 80's), we are not changing it, since we have an important community of Shadow users. In fact, they were able to manage the new product without training. As a note, there are import tools in the Shadow Tools menu, allowing you to import old Shadow files and workspaces.

**Comment by lucarebuffi** [comment]
Look at the renderings:

Cylindric mirror:

![screen shot 2016-11-29 at 12 37 23](https://cloud.githubusercontent.com/assets/6713598/20708534/a9fb8c9a-b630-11e6-8d37-edd543747bf4.png)

paraboloid:

![screen shot 2016-11-29 at 12 36 41](https://cloud.githubusercontent.com/assets/6713598/20708547/b29bea98-b630-11e6-9c9f-1ebfdace8cda.png)

**Comment by srio** [comment]
Some ideas and hints: 

1) In Shadow, you start chosing a mirror shape that is a 2D revolution surface (if conic) or toroid. At this point you expect 2D focusing. If you want to collimate a beam, or focus a collimated beam, use paraboloid. If you want point-to-point focus, start with ellipsoidal.

You see, there is no "cylindrical mirror" at this point. 

2) Yo may want to focus in one direction and not in the other. At this point, the surface in one direction becomes flat. So your mirror become a "cylinder" in the wide sense of the term.

If the direction that becomes flat is the sagittal one (i.e., you want to focus only in meridional direction), the angle between the cylinder axis and the x axis is ZERO. In this case:
- The cilynder can have a circular section (You started from a Sphere)  
- The cilynder can have an elliptical  section (You started from a Ellipsoid)
-The cylinder can have a parabolic section (You start from Paraboloid)

You may want to focus in sagittal direction only. In this case the cylinder axis and the x axis form an angle of 90 DEGREES. Pay attention that in this case the sagittal section of ANY revolution conic is always a circle, to it does not make sense to use Parabolic or Elliptical mirrors. Use the Spherical mirror (the simplest one)

Do not use toroidal mirror if you want a cylinder. Use Spherical instead. 

3) If you want to test shapes, start with a consequent source geometry. 

If you want to test paraboloids, start with a collimated source (e.g., a rectangle size with zero divergence). This beam should be focused downstream the mirror at a distance equal to the focal distance. 

If you want to test point to point focusing, you can compare toroids with ellipsoids, for example. See for example the tutorial 15 in  https://github.com/srio/ShadowOui-Tutorial

Start playing with a single focusing device, then think in combining several ones. 

Shadow helps you to define the right mirror parameters giving the focal distances. You can see the results using the "Info" widget. Also, you can enter externally the mirror parameters, or the conic coefficients. After playing a bit with some examples, you may go fromn one to another in a quite transparent way. 


Hope this help!

Manuel-

**Comment by lucarebuffi** [comment]
Second Point:

Firstly: **The re-calulation of the maj. and min. radius of the toroid is done after "enter" or "run shadow" and is not done when clicking on "render surface shape"**

Of course! the rendering refers to the OUTPUT of the ray-tracing. If you change the input parameters and you don't perform the ray-tracing again, the rendering will refer to the last result you have.

**Comment by lucarebuffi** [comment]
then:

"When defining the limits in the dimensions of the toroid, a double curved surface is displayed. When rendering the surface shape with "limit checks on" - a single curved surface is displayed."

No, it is just changing the scale, but the equation is identical. When infinite, the rendering takes an arbitrarily 10x10 surface, when finite, it renders the real shape

Finite:
![screen shot 2016-11-29 at 12 43 40](https://cloud.githubusercontent.com/assets/6713598/20708731/9ffeaf64-b631-11e6-8702-9eff9adc9a87.png)

Infinite:
![screen shot 2016-11-29 at 12 41 40](https://cloud.githubusercontent.com/assets/6713598/20708737/a7fc0734-b631-11e6-9cda-6e076a7d58d1.png)

**Comment by lucarebuffi** [comment]
An important note: With the right mouse button on a widget you have the possibility to copy the OE parameters and, in a similar way, paste to into a different widget. This is the way to rapidly create and test the same mirror with different shapes, ex.:

Copy parameter from paraboloid
![screen shot 2016-11-29 at 12 49 51](https://cloud.githubusercontent.com/assets/6713598/20708898/71290fa8-b632-11e6-9e38-7d1063eebf4f.png)

Paste to a new elliptical one:

![screen shot 2016-11-29 at 12 49 57](https://cloud.githubusercontent.com/assets/6713598/20708904/7dedd908-b632-11e6-8a5e-8b02ab77a385.png)

As a result, you'll have a identical mirror in terms of position, dimension, reflectivity and focus specification, excepting the parameters that are not sharable.

**Comment by paramirror** [comment]
Thank you for the detailed explaination and hints to both of you 
– finally my problem works.
Simply I havn’t tried out all possible combinations… ;)

But to understand finally the terminology
a)
„Paraboloid“  =  rotation of a parabola around its symmetry axis – spherical or more general an elliptical paraboloid
(tangential plane– parabola and sagittal plane – spherical/elliptical)
(both directions curved)
b)
„Cylindric mirror with parabolic profile“  =  parabolic cylinder
with two possible orientations as described in your examples.
only one direction is curved - single curvature

**Comment by srio** [comment]
>>> „Paraboloid“ = rotation of a parabola around its symmetry axis – 
YES  - In Shadow the symmetry axis is Y.

>>> spherical or more general an elliptical paraboloid
(tangential plane– parabola and sagittal plane – spherical/elliptical)
(both directions curved)

NO - The ROTATION paraboloid cannot be elliptic if you cut it with i) a plane containing the Y axis (tangential), or ii) perpendicular to it (Sagittal). The section of a revolution paraboloid with a plane perpendicular to the rotation axis (Y) is always a circle (because is a "rotation" paraboloid). 

>>> „Cylindric mirror with parabolic profile“ = parabolic cylinder

YES (this is a definition)

>> with two possible orientations as described in your examples.
only one direction is curved - single curvature

In Shadow, two possible orientations: 

i) Angle x and cylinder axis = ZERO: You get a cylinder whose section is a PARABOLA or "parabolic cylinder" (Tangential)

ii) Angle x and cylinder axis = 90 deg: You get  cylinder whose section is a CIRCLE (Sagittal)


As a rule of thumb: if you want to focus in sagittal direction, the shape of the cylinder is circular (never elliptical or Gaussian). The thing is the radius of the circle can be i) Fixed (CYLINDER), or ii) VARIABLE, in this case is not a cylinder but another thing. So for sagittal focusing the section is always circular, with i) constant radius (first approximation) you get a CYLINDER, ii) with radius changing linearly along Y you get a mirror like a cone (not implemented in shadow), and iii) with radius changing "in an optimum manner" you get the ellipsoid.

**Comment by lucarebuffi** [comment]
As a finale note: Who are you? I can't figure out your name :D
