### ISSUE TITLE
ShadowOui for beginner

### ISSUE THREAD

**Issue by elglanto** [lucarebuffi/ShadowOui#165]
Have starter to work with the software and had a good look at the exemples. I would like to use it to design simple beamlines for a flat field spectrometer. For that, I am starting with some very basic things to try to understand. e.g. a geometrical source and a spherical mirror. However, there are still some things that I don't understand. Hopefully this is the right place to ask some questions. Otherwise, I would be happy to be directed towards a more proper place.

Here is what I don't get. First, I have a Gaussian geometrical source with a flat angular distribution and no temporal shape thus no depth. The energy distribution is a single line at 100 nm.
Then, with a plane mirror 100 mm away, I look at the footprint (I understand it to be the beam on the mirror surface) while changing the angle of incidence and I get similar footprints than what I would get with basic analytical equations: the beam gets elliptical on the Y-axis.
My issue comes now. When I replace the plane mirror with a spherical one and place it at a somehow grazing indicence (80 degrees), the footprint looks like a coma along the Y-axis and this effect increases while the spherical radius decreases. This effect is then seen on the image plane.

In both cases, the mirrors dimensions have been set to be infinite.

Thus, I am wondering if I am missing something in ShadowOui or if I forgot some very simple optical lectures. Thanks for any help.

**Comment by srio** [comment]
Could you please post a screenshot of the main windows used? Or better submit the workspace? With that we could look into it. Thanks

**Comment by elglanto** [comment]
Thanks for your answer. I would assume the workspace is the .pws file. I uploaded there:
https://drive.google.com/open?id=0B6kQVWZI95xeNllLSUREN2d3QXc
There is a plot X,Y widged which plots the beam 10 mm after the mirror. If you put 50 mm instead you will see the coma like beam.

**Comment by srio** [comment]
I think everything is correct. For example Theta=80 deg  R=200: 
![image](https://cloud.githubusercontent.com/assets/502315/22285527/4db903c0-e2ec-11e6-8252-98b542eca091.png)

(note a slight asymmetry in Y and Lost rays =0)

If we go to a very narrow radius (R=20): 
![image](https://cloud.githubusercontent.com/assets/502315/22285581/87ac4682-e2ec-11e6-9566-f26811774ed2.png)


You see that the Y histogram is more asymmetric (the spread of the beam on the mirror surface is not homogeneous, is more concentrated for Y>0 (downstream the mirror pole)) and you see some rays are lost (see lost rays) because the curvature is high enough to not accepting all the beam. 


A bit elaborated is to plot the mirror profile. Use the file with the beam onto the mirror (mirr.01) and visualize Z vs Y (you see the non-uniform illumination): 

![image](https://cloud.githubusercontent.com/assets/502315/22285764/43b76ffa-e2ed-11e6-83eb-b3adde9878a9.png)

![image](https://cloud.githubusercontent.com/assets/502315/22285785/55dde614-e2ed-11e6-915b-54618fc67620.png)

**Comment by elglanto** [comment]
Thanks for your answer. I made a small drawing for myself to see why I was wrong... Tha analysis with mirr.01 was very helpfull.

I would ten have two questions regarding thos analysing files.
1) In the ShadowOui interface, How do I know the optical element number in order to make sure that the file mirr.xx is analysing the optical element I think it analyses?
2) Currently, the files are labeled from .01 to .04. If I want to analyse the 5th element, do I just duplicate one file and call it mirr.05 or do I have to modify code in the file itself? I would assume that it is the first guess since so far, I haven't been able to properly read those files.

**Comment by elglanto** [comment]
Hello, I am allowing myself to make a little bump regarding my last message.
