### ISSUE TITLE
How to install ShadowOui add-on in Orange3?

### ISSUE THREAD

**Issue by maurov** [lucarebuffi/ShadowOui#35]
Hi Luca,

I see that OASYS1 is no more under development, so I assume ShadowOui has to be installed directly as add-on under Orange3. Am I right? If yes, how to do it?

I have installed first a working version of orange3 (v3.2 from Github), then `python setup.py install` of ShadowOui. I can correctly import everything from python, but I do not get ShadowOui objects in the Orange GUI.

Thanks for your help,
Mauro

**Comment by lucarebuffi** [comment]
Dear Mauro, 
I guess you are a linux user, please check this page:

http://www.elettra.eu/lightsources/labs-and-services/hard-soft-x-ray-optical-engineering/oasys.html

oasys is no more a separate branch of Orange and even Orange changed its structure:

in order to install properly the libraries you should not install Orange (remove it!), but follow the instructions published into the installation manual.

By the way if you already have:
numpy >= 1.9.2, scipy >= 0.15.1, matplotlib >= 1.4.3 
xraylib 
PyMca5 (5.1.0)
Shadow (it can now be installed via: pip install pykern, pip install shadow3)

you can install oasys with these commands:

pip install orangecanvas
pip install orangewidget
pip install oasys

then:

sudo python -m oasys.canvas

go to the add-on form (directly from the welcome form) e install ShadowOui.

**Comment by maurov** [comment]
Thanks, great!

Everything went fine under Linux (Ubuntu 14.04, installed in a virtual environment - no need to use sudo then), apart the last step to install ShadowOui add-on.

The problem is that I'm using a proxy server to connect to the internet and this is not taken into account by the GUI. One should check the `HTTP_PROXY` or `HTTPS_PROXY` environmental variable or just set it in the preferences of the GUI.

**Comment by lucarebuffi** [comment]
Yes, you should set the environmental variable for the proxy:

export https_proxy="http://<proxy.server>:<port>"
export http_proxy="http://<proxy.server>:<port>"

This feature won't be integrated into Oasys. The best you can do is to set them into your profile (as well as the other two indicated at the end of the manual)

**Comment by maurov** [comment]
Sure, these variables were already set in my profile, but still does not work!

**Comment by lucarebuffi** [comment]
I suggest you to check it directly with Manuel Sanchez del Rio, I am possibly missing something.
He can deal with updates through pip.

**Comment by maurov** [comment]
OK, problem solved with the help of Manuel. I report here the working procedure (for documentation).

The working procedure to install ShadowOui add-on in case of behind a proxy (once the GUI is correctly installed, check with `python -m oasys.canvas`):

- `git clone` ShadowOui repository somewhere
- (within a virtual environment or with superuser rights, with python3.4) `python setup.py sdist develop`

That's all! Then the objects should appear in the GUI (check with `python -m orange.canvas`)

**Comment by lucarebuffi** [comment]
This is a trick and not a real solution, you are not installing the add-on, you are telling python to point to a local copy of the sources through a link in the dist-packages directory. If you find the way to let pip work properly behind the ESRF proxy, please let us know in order to update the troubleshooting part of the manual. SOLEIL users were able to bypass the proxy with the environmental variables.
