### ISSUE TITLE
error when running Bragg preprocessor

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#85]
![image](https://cloud.githubusercontent.com/assets/502315/12722148/dceb8c74-c903-11e5-8169-e51e31004f95.png)

got it in both Linux and Mac!! Please help...

**Comment by lucarebuffi** [comment]
I knew it, I didn't fixed yet. For the moment, just reselect the Crystal descriptor and it works

**Comment by lucarebuffi** [comment]
this is not properly a Bug. We just release the new version where the crystal descriptor comes from a combo box, so the attribute "DESCRIPTOR" changed its type form string to integer (it is the index of the combo box). When reading old projects, before the modification, the attribute is initialized to string and if you don't change it by interacting with the combo you have this error. It is better to introduce a check in order to avoid such a problem.
