### ISSUE TITLE
Incident angles in optical elements

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#87]
I see you changed the inputs to set angles with respect to the surface or to the normal (Ruben;s request if I remember well).

This is OK, but now when I define the focal distances and angle (Surface Shape-Internal calculated), I need my calculator for input the angle in degrees with respect to the normal if I used mrad to the surface in th ePosition panel. Before, I just copy/paste the number in the position panel. This is a bit annoying. 

To end with a clean solution, I propose you to replicate the items from the position panel:
![image](https://cloud.githubusercontent.com/assets/502315/12743614/2fbd2c06-c98f-11e5-93b7-cd6326a2f18c.png)
to the position panel: 
![image](https://cloud.githubusercontent.com/assets/502315/12743670/83530d0e-c98f-11e5-83f9-d1696451c9a6.png)

**Comment by lucarebuffi** [comment]
I was thinking the same, because even the previous copy/paste action is a little bit annoying...

**Comment by SergioLordano** [comment]
On this subject, it is often needed to adjust the incidence angles in minor increments (for instance, to mitigate some astigmatism, or for misalignment purposes). I generally use the [mrad] option with respect to surface. 
The problem is that the value that is actually passed to shadow is the one in [deg], respect to the normal, which is converted from [mrad] and rounded with 3 decimal numbers. So when the increment is less than 17.5 urad (or 0.001 deg), the angle does not really change (and sometimes the focusing is sensitive to much smaller angles).  
If it is as simple as it seems, I would suggest to pass the [deg] value to shadow with more resolution, also for a better precision, in general.

**Comment by lucarebuffi** [comment]
You are doing it in the wrong way. You should use the O.E. Movements options:

![screen shot 2019-02-19 at 10 38 14 am](https://user-images.githubusercontent.com/6713598/53031454-81129a80-3432-11e9-85da-7a78ae625382.png)

**Comment by lucarebuffi** [comment]
The X rotation corresponds to the Pitch, Y rotation to Roll and Z to Yaw.

**Comment by lucarebuffi** [comment]
Then, the field actually used by shadow3 is the field in degrees, the one in mrad is for the user. That field has 6 decimal digits allowed (gratings needs very fine tuning).
Anyway, I will allow more digits in the mrad field in the next SahdowOui release.

**Comment by SergioLordano** [comment]
Hi Luca, I use O. E. Movements as well, but sometimes we want the optical axis to keep following the principal ray (as you mentioned, about the gratings), which does not happen if I use the O. E. Movements. 
Thank you for allowing the extra digits!

**Comment by lucarebuffi** [comment]
I repeat: use the degrees field, that is the field actually used by shadow3. The value that is passed from the guy to the kernel is that one and not the mrad one.

**Comment by lucarebuffi** [comment]
The degrees field has 10 decimal digits, the mrad field has decimal 7 digits for gratings and 2 for all the other. I will change this.
